### ISSUE TITLE
adding to chrome

### ISSUE THREAD

**Issue by subrama** [mehmetc/primo-explorer#2]
Chrome does not let me add the extension as it says it needs to be listed in the chrome web store.
Any ideas on how I can make it work?

Anna

**Comment by mehmetc** [comment]
Hi Anna,

The newUI February 2017 release broke a lot of things. ExLibris moved from the ngForward to ng-metadata library and that gave a 50% code improvement but at the same time made this tool useless.

I'm working on an alternative tool that integrates into Primo. It is still in development and I have to write some documentation for it. I hope to do this in the coming weeks but you can already have a look at it [primo-explore-dom](https://github.com/mehmetc/primo-explore-dom). It follows the same principle as a customView package. 

Let me know if you get stuck.

Mehmet
